product:
      id: DEV302   
                    
#Eureka Config
eureka: 
  instance: 
    prefer-ip-address: true
  client:   
    fetch-registry: true
    register-with-eureka: true
    serviceUrl: 
       defaultZone: http://${server.host}:8761/eureka/
#Actuator configuration
management: 
       endpoints:
               web:
                 exposure:
                        include: '*'                   
                        


